runner:
  scope: repo

  replicas:
    minimum: 0
    maximum: 5

  resources:
    limits:
      cpu: 2
      memory: 2Gi
    
    requests:
      cpu: 2
      memory: 256Mi

  nodeSelector:
    lsc-sde.nhs.uk/nodeType: github-runner

accessToken:
  secretName: pat-token
  secretKey: token