runner:
  scope: repo

  replicas:
    minimum: 0
    maximum: 5

  resources:
    limits:
      cpu: 1
      memory: 2Gi
    
    requests:
      cpu: 100m
      memory: 256Mi

accessToken:
  secretName: pat-token
  secretKey: token