apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: github-runner
configMapGenerator:
  - name: environment-config
    files:
      - values.yaml=environment-config.yaml
resources:
  - repository.yaml
  - runners
  - secret.yaml
  - secret-job.yaml