apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: github-runner
configMapGenerator:
  - name: datascience-notebook
    files:
      - values.yaml=runner-config.yaml
generatorOptions:
  disableNameSuffixHash: true
resources:
  - release.yaml