github:
  scope: org
  org: lsc-sde

runner:
  labels: linux,lsc-sde

  replicas:
    minimum: 0
    maximum: 5

  resources:
    requests:
      cpu: 10m
      memory: 256Mi

accessToken:
  secretName: pat-token
  secretKey: token