apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: datascience-notebook
  annotations:
    lsc-sde.nhs.uk/definitionVersion: "1.0.1"
spec:
  targetNamespace: github-runner
  releaseName: datascience-notebook
  chart:
    spec:
      chart: github-actions-runner
      sourceRef:
        kind: HelmRepository
        name: github-runner
        namespace: github-runner
  interval: 5m0s
  install:
    remediation:
      retries: -1
    disableWait: true
    disableWaitForJobs: true
  upgrade:
    remediation:
      retries: -1
    disableWait: true
    disableWaitForJobs: true
  values:
    github:
      repository: docker-datascience-notebook

    runner:
      scope: repo
      labels: linux,datascience-notebook

      replicas:
        minimum: 0
        maximum: 5


      resources:
        limits:
          cpu: 2
        
        requests:
          cpu: 2
          memory: 256Mi

      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: lsc-sde.nhs.uk/nodeType
                operator: In
                values:
                - github-runner

    accessToken:
      secretName: pat-token
      secretKey: token