apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: github-runner
configMapGenerator:
  - name: environment-config
    files:
      - values.yaml=environment-config.yaml
generatorOptions:
  disableNameSuffixHash: true
resources:
  - secret.yaml
  - secret-job.yaml
spec:
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-config
        namespace: lscsde-config