apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: github-runner
configMapGenerator:
  - name: environment-config
    files:
      - values.yaml=environment-config.yaml
generatorOptions:
  disableNameSuffixHash: true
resources:
  - secret.yaml
  - secret-job.yaml
replacements:
  - source:
      name: cluster-config
      namespace: lscsde-config
      kind: ConfigMap
      version: v1
      fieldPath: data.AZURE_CLIENT_ID
    targets:
    - select:
        kind: SecretProviderClass
        name: pat-token-sync
      fieldPaths:
      - spec.parameters.userAssignedIdentityID
  - source:
      name: cluster-config
      namespace: lscsde-config
      kind: ConfigMap
      version: v1
      fieldPath: data.AZURE_KEYVAULT_NAME
    targets:
    - select:
        kind: SecretProviderClass
        name: pat-token-sync
      fieldPaths:
      - spec.parameters.keyvaultName
    targets:
    - select:
        kind: SecretProviderClass
        name: pat-token-sync
      fieldPaths:
      - spec.parameters.userAssignedIdentityID
  - source:
      name: cluster-config
      namespace: lscsde-config
      kind: ConfigMap
      version: v1
      fieldPath: data.AZURE_TENANT_ID
    targets:
    - select:
        kind: SecretProviderClass
        name: pat-token-sync
      fieldPaths:
      - spec.parameters.tenantId