apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: runners
  annotations:
    lsc-sde.nhs.uk/definitionVersion: "1.0.7"
spec:
  targetNamespace: github-runner
  releaseName: runners
  chart:
    spec:
      chart: github-actions-runner
      version: ${github_runner_chart_version}
      sourceRef:
        kind: HelmRepository
        name: github-runner
        namespace: github-runner
  interval: 5m0s
  install:
    remediation:
      retries: -1
    disableWait: true
    disableWaitForJobs: true
  upgrade:
    remediation:
      retries: -1
    disableWait: true
    disableWaitForJobs: true
  valuesFrom:
  - kind: ConfigMap
    name: runner-config

  - kind: ConfigMap
    name: environment-config
