name: Create Release Branch from Main

on:
  workflow_dispatch:
  push:
    branches:
    - 'main'

jobs:
  package:
    uses: lsc-sde/lsc-sde/.github/workflows/flux-release.yaml@main
    with:
      directory: iac/flux/github-action-runners
      yamlPath: github_runner
    secrets: inherit
